name: ethio_explore
description: "Explore Ethiopia — offline-first travel companion."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # ── Icons ──────────────────────────────────────────────
  cupertino_icons: ^1.0.8

  # ── Local persistence (offline storage) ────────────────
  shared_preferences: ^2.5.5

  # ── Interactive maps ────────────────────────────────────
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # ── URL launcher (for map directions) ──────────────────
  url_launcher: ^6.3.0
  http: ^1.2.2
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "Logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - Logo.png
